name: Run Python scripts

on:
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run mock_db.py
      run: python mock_db.py

    - name: Run data_join.py
      run: python data_join.py

    - name: Run data_quality.py
      run: python data_quality.py